name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to s3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      
      - name: Configure AWS Credentials
        uses: actions/setup-aws-credentials@v2
        with:
          aws-access-key: "${{secrets.AWS_ACCESS_KEY}}"
          aws-secret-key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          aws-region: "${{secrets.AWS_DEFAULT_REGION}}"

      - name: IaC Apply
        env: 
          COMMAND_IAC: terraform
        run: |
          cd infrastructure
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
          $COMMAND_IAC apply -auto-approve